// These styles apply to every route in the application
import NavbarSection from '@/components/NavbarSection'
import './globals.css'
import UseScrollhash from '@/client_components/UseScrollhash'
import FooterSection from '@/components/FooterSection'


export const metadata = {
  title: 'Thejus Joseph',
  description: 'Generated by Thejus Joseph',
}

export default function RootLayout({ children }) {
  <link
    rel="icon"
    href="/icon?<generated>"
    type="image/<generated>"
    sizes="<generated>"
  />
  return (
    
    <html lang="en" data-theme="light" className="bg-[#f5f6f0]" >
      <body >
        <NavbarSection scroll={UseScrollhash} />
        {children}
        <FooterSection scroll={UseScrollhash}/>
        </body>
    </html>
  )
}